### ISSUE TITLE
withResourceName does not work

### ISSUE THREAD

**Issue by DesmondPang** [spatie/fractalistic#11]
withResourceName does not work. Could not change the resource name. I use Laravel 5.4.

**Comment by freekmurze** [comment]
The tests seem to indicate that this is working properly

https://github.com/spatie/fractalistic/blob/master/tests/ResourceNameTest.php

Could you PR a failing test?

**Comment by DesmondPang** [comment]
OMG, I totally got a wrong idea about the ResourceName. I checked your JsonApiSerializer(). The resource name refers to the "type" of each item.

What I thought is the ResourceName could replace the "data" key of the output data. Just like the following result. the default "data" key is replaced by "books"
```Json
{
	"books":[
		{
			"id":1
		},
		{
			"id":2
		}
	],
	"meta":{
		...
	}
}
```
Sorry about for my mistake.

**Comment by freekmurze** [comment]
No problem!
