### ISSUE TITLE
Support for fractal 0.16

### ISSUE THREAD

**Issue by JonasDoebertin** [spatie/fractalistic#13]
Are there any incompatibilities with league/fractal 0.16? If not, what about allowing that version, too?

**Comment by sebastiandedeyne** [comment]
Should work, giving it a spin now. Will report back later!

**Comment by sebastiandedeyne** [comment]
Travis says no: https://travis-ci.org/spatie/fractalistic/jobs/225539708

Apparently some changes that break our tests. I'll look into it soon.

**Comment by freekmurze** [comment]
Compatibility with fractal 0.16 has arrived in `v2` of Fractalistic

**Comment by JonasDoebertin** [comment]
You're fast! Thank you so much!
