### ISSUE TITLE
No support for sparse fieldsets

### ISSUE THREAD

**Issue by Dadibom** [spatie/fractalistic#19]
See this PR: https://github.com/thephpleague/fractal/pull/273

**Comment by freekmurze** [comment]
If you need this quick, I'd accept a PR.

**Comment by Dadibom** [comment]
Sure thing!

**Comment by Dadibom** [comment]
https://github.com/spatie/fractalistic/pull/20

**Comment by freekmurze** [comment]
Closing this, we'll handle it further in the PR.
