### ISSUE TITLE
Question concerning includes

### ISSUE THREAD

**Issue by seblavoie** [spatie/fractalistic#25]
Hello! First off, thanks for the package :) I have a question concerning the includes and the manager. I am trying to do something similar as what's in [Fractal's documentation](http://fractal.thephpleague.com/transformers/#including-data) concerning includes and I don't get how I can do with this package.

I would like to have different includes available and be able to include them from the querystring.

Here what Fractal's documentation says:

> ```
> <?php namespace App\Transformer;
> 
> use Acme\Model\Book;
> use League\Fractal\TransformerAbstract;
> 
> class BookTransformer extends TransformerAbstract
> {
>     /**
>      * List of resources possible to include
>      *
>      * @var array
>      */
>     protected $availableIncludes = [
>         'author'
>     ];
> 
>     /**
>      * Turn this item object into a generic array
>      *
>      * @return array
>      */
>     public function transform(Book $book)
>     {
>         return [
>             'id'    => (int) $book->id,
>             'title' => $book->title,
>             'year'    => (int) $book->yr,
>             'links'   => [
>                 [
>                     'rel' => 'self',
>                     'uri' => '/books/'.$book->id,
>                 ]
>             ],
>         ];
>     }
> 
>     /**
>      * Include Author
>      *
>      * @return League\Fractal\ItemResource
>      */
>     public function includeAuthor(Book $book)
>     {
>         $author = $book->author;
> 
>         return $this->item($author, new AuthorTransformer);
>     }
> }
> ```
> These includes will be available but can never be requested unless the Manager::parseIncludes() method is called:
> ```
> <?php
> use League\Fractal;
> 
> $fractal = new Fractal\Manager();
> 
> if (isset($_GET['include'])) {
>     $fractal->parseIncludes($_GET['include']);
> }
> ```
> With this set, include can do some great stuff. If a client application were to call the URL /books?include=author then they would see author data in the response.

Now, I understand from Fractalistic documentation that I can manually include or exclude relationships, but is there a way to do as in the example above and let it be customizable from the querystring globally?

**Comment by sebastiandedeyne** [comment]
This depends more on your framework than this package. Fractalistic also exposes a `parseIncludes` method, in which you can do the same as in the docs.

For example, if you'd be using Laravel...

```
$fractal->parseIncludes(request()->get('include'));
```

**Comment by seblavoie** [comment]
Ah yes, thank you! I am indeed using Laravel and this was exactly the piece I was missing. Thanks for the quick answer and for the great packages 👍
