### ISSUE TITLE
Paginator links property is either array or object

### ISSUE THREAD

**Issue by tomvo** [spatie/fractalistic#36]
I've checked in both this repo as well as `laravel-fractal` and I believe my issue originates here. I'm noticing an issue with the `paginateWith` method which adds pagination info to the `meta` key in my json responses.
When there are no links for the pagination the meta property looks like this:

```
"meta": {
        "pagination": {
...
            "links": []
        }
    }
```

When there are, it looks like this:

```
"meta": {
        "pagination": {
...
            "links": {
                "next": "[url]"
            }
        }
    }
```

You can see that in an empty resultset the `links` property is an array and when set, it's an object. This causes issues for client implementing our API. Any idea on where to fix this?

**Comment by freekmurze** [comment]
I'd accept a PR (with tests) that fixes this.

**Comment by tomvo** [comment]
thanks @freekmurze but I checked a little more and it seems the issue is caused by the ArraySerializer (or JsonApiSerializer) in fractal itself, see here: https://github.com/thephpleague/fractal/issues/433. Of course we could overload the method in the fractalistic library or even just for my scenario but I'd be interested to hear from the php league guys.

**Comment by freekmurze** [comment]
If it's a bug it should be solved in the league's package.
