### ISSUE TITLE
Custom Scope injection

### ISSUE THREAD

**Issue by Firtzberg** [spatie/fractalistic#42]
I want to use a custom Scope implementation.
The League's package allows using it by injecting a custom ScopeFactory into the Manager.
I don't see a way to do this since Spatie\Fractalistic\Fractal creates an instance without arguments.

**Comment by freekmurze** [comment]
Currently we're not actively adding features ourselves to this package. If you need something, send a PR with tests and an updated readme and we'll review it 👍
