### ISSUE TITLE
Fractal::jsonSerialize() triggers a Type error (PHP 7.4.24)

### ISSUE THREAD

**Issue by albertoarena** [spatie/fractalistic#54]
This change done to support PHP 8.1 triggers a `Type error`.

Commit:
https://github.com/spatie/fractalistic/commit/4d3b8a68b6575e9b0202e842977c9c29224fd9ac#diff-9ebff18d48644c7d6e2c1006245d57ef9028099e796f76f967c8656aedadcf4bR458

Change:
https://github.com/spatie/fractalistic/blob/5a89b24d3153a9c4b17cd1ed523b0a5ef9143558/src/Fractal.php#L458

Error:

```
TypeError
Return value of Spatie\Fractalistic\Fractal::jsonSerialize() must be an instance of Spatie\Fractalistic\mixed, array returned 
```

Reason:
- `Fractal::toArray` return type is `array`
- `Fractal::jsonSerialize()` return type os `mixed`

Further details:
- PHP version: 7.4.24

**Comment by freekmurze** [comment]
The tests seem to indicate that it's working fine. Could you submit a PR with a failing tests (and maybe also the fix)?

**Comment by albertoarena** [comment]
@freekmurze I have a fix ready, tested with php 7.4 and 8.1, but I am not allowed to create a pull request.

Should I be added to contributors?

Thanks

**Comment by freekmurze** [comment]
Creating pull requests is not restricted in any way.

**Comment by albertoarena** [comment]
PR: https://github.com/spatie/fractalistic/pull/55

**Comment by freekmurze** [comment]
We'll handle this further in #55
